config/routes.rb
Testing::Application.routes.draw do
  resources :colors

  resources :blocks

  resources :text_posts

  get "home/index"

  root :to => "home#index"

end

app/models/block.rb
class Block < ActiveRecord::Base
  attr_accessible :blue, :float, :green, :red
end

app/models/color.rb
class Color < ActiveRecord::Base
  attr_accessible :blue, :green, :red
end

app/models/text_post.rb
class TextPost < ActiveRecord::Base
  attr_accessible :body, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  # GET /blocks
  # GET /blocks.json
  def index
    @blocks = Block.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blocks }
    end
  end

  # GET /blocks/1
  # GET /blocks/1.json
  def show
    @block = Block.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @block }
    end
  end

  # GET /blocks/new
  # GET /blocks/new.json
  def new
    @block = Block.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @block }
    end
  end

  # GET /blocks/1/edit
  def edit
    @block = Block.find(params[:id])
  end

  # POST /blocks
  # POST /blocks.json
  def create
    @block = Block.new(params[:block])

    respond_to do |format|
      if @block.save
        format.html { redirect_to @block, notice: 'Block was successfully created.' }
        format.json { render json: @block, status: :created, location: @block }
      else
        format.html { render action: "new" }
        format.json { render json: @block.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blocks/1
  # PUT /blocks/1.json
  def update
    @block = Block.find(params[:id])

    respond_to do |format|
      if @block.update_attributes(params[:block])
        format.html { redirect_to @block, notice: 'Block was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @block.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blocks/1
  # DELETE /blocks/1.json
  def destroy
    @block = Block.find(params[:id])
    @block.destroy

    respond_to do |format|
      format.html { redirect_to blocks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  # GET /colors
  # GET /colors.json
  def index
    @colors = Color.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @colors }
    end
  end

  # GET /colors/1
  # GET /colors/1.json
  def show
    @color = Color.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @color }
    end
  end

  # GET /colors/new
  # GET /colors/new.json
  def new
    @color = Color.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @color }
    end
  end

  # GET /colors/1/edit
  def edit
    @color = Color.find(params[:id])
  end

  # POST /colors
  # POST /colors.json
  def create
    @color = Color.new(params[:color])

    respond_to do |format|
      if @color.save
        format.html { redirect_to @color, notice: 'Color was successfully created.' }
        format.json { render json: @color, status: :created, location: @color }
      else
        format.html { render action: "new" }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /colors/1
  # PUT /colors/1.json
  def update
    @color = Color.find(params[:id])

    respond_to do |format|
      if @color.update_attributes(params[:color])
        format.html { redirect_to @color, notice: 'Color was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colors/1
  # DELETE /colors/1.json
  def destroy
    @color = Color.find(params[:id])
    @color.destroy

    respond_to do |format|
      format.html { redirect_to colors_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
    

    
  end
  
end

app/controllers/text_posts_controller.rb
class TextPostsController < ApplicationController
  # GET /text_posts
  # GET /text_posts.json
  def index
    @text_posts = TextPost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @text_posts }
    end
  end

  # GET /text_posts/1
  # GET /text_posts/1.json
  def show
    @text_post = TextPost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @text_post }
    end
  end

  # GET /text_posts/new
  # GET /text_posts/new.json
  def new
    @text_post = TextPost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @text_post }
    end
  end

  # GET /text_posts/1/edit
  def edit
    @text_post = TextPost.find(params[:id])
  end

  # POST /text_posts
  # POST /text_posts.json
  def create
    @text_post = TextPost.new(params[:text_post])

    respond_to do |format|
      if @text_post.save
        format.html { redirect_to @text_post, notice: 'Text post was successfully created.' }
        format.json { render json: @text_post, status: :created, location: @text_post }
      else
        format.html { render action: "new" }
        format.json { render json: @text_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /text_posts/1
  # PUT /text_posts/1.json
  def update
    @text_post = TextPost.find(params[:id])

    respond_to do |format|
      if @text_post.update_attributes(params[:text_post])
        format.html { redirect_to @text_post, notice: 'Text post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @text_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /text_posts/1
  # DELETE /text_posts/1.json
  def destroy
    @text_post = TextPost.find(params[:id])
    @text_post.destroy

    respond_to do |format|
      format.html { redirect_to text_posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/text_posts_helper.rb
module TextPostsHelper
end

app/views/blocks/_form.html.erb
<%= form_for(@block) do |f| %>
  <% if @block.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@block.errors.count, "error") %> prohibited this block from being saved:</h2>

      <ul>
      <% @block.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :red %><br />
    <%= f.text_field :red %>
  </div>
  <div class="field">
    <%= f.label :green %><br />
    <%= f.text_field :green %>
  </div>
  <div class="field">
    <%= f.label :blue %><br />
    <%= f.text_field :blue %>
  </div>
  <div class="field">
    <%= f.label :float %><br />
    <%= f.text_field :float %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blocks/edit.html.erb
<h1>Editing block</h1>

<%= render 'form' %>

<%= link_to 'Show', @block %> |
<%= link_to 'Back', blocks_path %>

app/views/blocks/index.html.erb
<h1>Listing blocks</h1>

<table>
  <tr>
    <th>Red</th>
    <th>Green</th>
    <th>Blue</th>
    <th>Float</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blocks.each do |block| %>
  <tr>
    <td><%= block.red %></td>
    <td><%= block.green %></td>
    <td><%= block.blue %></td>
    <td><%= block.float %></td>
    <td><%= link_to 'Show', block %></td>
    <td><%= link_to 'Edit', edit_block_path(block) %></td>
    <td><%= link_to 'Destroy', block, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Block', new_block_path %>

app/views/blocks/new.html.erb
<h1>New block</h1>

<%= render 'form' %>

<%= link_to 'Back', blocks_path %>

app/views/blocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Red:</b>
  <%= @block.red %>
</p>

<p>
  <b>Green:</b>
  <%= @block.green %>
</p>

<p>
  <b>Blue:</b>
  <%= @block.blue %>
</p>

<p>
  <b>Float:</b>
  <%= @block.float %>
</p>


<%= link_to 'Edit', edit_block_path(@block) %> |
<%= link_to 'Back', blocks_path %>

app/views/colors/_form.html.erb
<%= form_for(@color) do |f| %>
  <% if @color.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@color.errors.count, "error") %> prohibited this color from being saved:</h2>

      <ul>
      <% @color.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :red %><br />
    <%= f.text_field :red %>
  </div>
  <div class="field">
    <%= f.label :green %><br />
    <%= f.text_field :green %>
  </div>
  <div class="field">
    <%= f.label :blue %><br />
    <%= f.text_field :blue %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/colors/edit.html.erb
<h1>Editing color</h1>

<%= render 'form' %>

<%= link_to 'Show', @color %> |
<%= link_to 'Back', colors_path %>

app/views/colors/index.html.erb
<h1>Listing colors</h1>

<table>
  <tr>
    <th>Red</th>
    <th>Green</th>
    <th>Blue</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @colors.each do |color| %>
  <tr>
    <td><%= color.red %></td>
    <td><%= color.green %></td>
    <td><%= color.blue %></td>
    <td><%= link_to 'Show', color %></td>
    <td><%= link_to 'Edit', edit_color_path(color) %></td>
    <td><%= link_to 'Destroy', color, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Color', new_color_path %>

app/views/colors/new.html.erb
<h1>New color</h1>

<%= render 'form' %>

<%= link_to 'Back', colors_path %>

app/views/colors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Red:</b>
  <%= @color.red %>
</p>

<p>
  <b>Green:</b>
  <%= @color.green %>
</p>

<p>
  <b>Blue:</b>
  <%= @color.blue %>
</p>


<%= link_to 'Edit', edit_color_path(@color) %> |
<%= link_to 'Back', colors_path %>

app/views/home/index.html.erb
<div class="container-fluid">
	
	<div class="topbar">

	</div>
		
	<div class="content">
		
		<div class="block mainblock">
		
		<%= link_to "Colors", colors_path %>
		
		</div>
	
		<div class="block secondblock">
		
		</div>
			
	
	</div>
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testing</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "bootstrap", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/text_posts/_form.html.erb
<%= form_for(@text_post) do |f| %>
  <% if @text_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@text_post.errors.count, "error") %> prohibited this text_post from being saved:</h2>

      <ul>
      <% @text_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/text_posts/edit.html.erb
<h1>Editing text_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @text_post %> |
<%= link_to 'Back', text_posts_path %>

app/views/text_posts/index.html.erb
<h1>Listing text_posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @text_posts.each do |text_post| %>
  <tr>
    <td><%= text_post.title %></td>
    <td><%= text_post.body %></td>
    <td><%= link_to 'Show', text_post %></td>
    <td><%= link_to 'Edit', edit_text_post_path(text_post) %></td>
    <td><%= link_to 'Destroy', text_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Text post', new_text_post_path %>

app/views/text_posts/new.html.erb
<h1>New text_post</h1>

<%= render 'form' %>

<%= link_to 'Back', text_posts_path %>

app/views/text_posts/show.html.erb
<div class="text_post">

<p>
  <b>Title:</b>
  <%= @text_post.title %>
</p>

<p>
  <b>Body:</b>
  <%= @text_post.body %>
</p>

</div>

<%= link_to 'Edit', edit_text_post_path(@text_post) %> |
<%= link_to 'Back', text_posts_path %>